### ISSUE TITLE
Onko Palvelut-näkymässä järkeä?

### ISSUE THREAD

**Issue by bsuuv** [bsuuv/Village-Newbies#15]
Tällä hetkellä siinä on lista kaikista asiakkaista, kaikista palveluista ja asiakkaan palveluista.

Onko mieltä listata asiakkaan palveluja, koska palvelut liittyvät enemmänkin tiettyyn varaukseen? Pitäisikö näkymässä mielummin olla näkymä kaikista palveluista ja mahdollisuus niiden muokkaamiseen?
Varaukset näkymässä puolestaan olisi sitten listattuna kaikki varaukset ja yksittäiseen näkymään liittyvät palvelut ja mökit. Varausnäkymään päädyttäisiin, kun klikataan asiakasnäkymässä tietyn asiakkaan varausta.
Asiakkaat näkymässä puolestaan olisi listattuna asiakkaat ja yksittäisen asiakkaan varaukset.

Perustuu kuviin, joita Discordissa on, saattaa olla turha kysymys, jos ootte muokannu sitä jo erilaiseksi. Tuli mieleen tämä ko tein PalveluidenHallinta-luokkaa ja huomasin, että asiakkaan palveluiden saamiseksi täytyy tehä vähän enemmän SQL-temppuja.

**Comment by sbuugilaine** [comment]
kohta on

Lähetetty Windows 10:n Sähköposti<https://go.microsoft.com/fwlink/?LinkId=550986>sta

________________________________
Lähettäjä: bsuuv <notifications@github.com>
Lähetetty: Wednesday, April 15, 2020 4:28:01 PM
Vastaanottaja: bsuuv/Village-Newbies <Village-Newbies@noreply.github.com>
Kopio: Peter <peter.puukilainen@hotmail.fi>; Assign <assign@noreply.github.com>
Aihe: Re: [bsuuv/Village-Newbies] Onko Palvelut-näkymässä järkeä? (#15)


Assigned #15<https://github.com/bsuuv/Village-Newbies/issues/15> to @sbuugilaine<https://github.com/sbuugilaine>.

**Comment by bsuuv** [comment]
Juu olite huomannu saman jutun jo aiemmin.

**Comment by sbuugilaine** [comment]
pitäis olla järkee nyt


Lähetetty Windows 10:n Sähköposti<https://go.microsoft.com/fwlink/?LinkId=550986>sta

________________________________
Lähettäjä: bsuuv <notifications@github.com>
Lähetetty: Wednesday, April 15, 2020 5:22:11 PM
Vastaanottaja: bsuuv/Village-Newbies <Village-Newbies@noreply.github.com>
Kopio: Peter <peter.puukilainen@hotmail.fi>; Mention <mention@noreply.github.com>
Aihe: Re: [bsuuv/Village-Newbies] Onko Palvelut-näkymässä järkeä? (#15)


Juu olite huomannu saman jutun jo aiemmin.
