### ISSUE TITLE
Palvelutyyppien toteuttaminen Palvelu-oliossa

### ISSUE THREAD

**Issue by bsuuv** [bsuuv/Village-Newbies#4]
Palvelu-oliossa on palvelun tyyppinä int. Ohjelmoidessa olisi kätevä nähdä selostettuna, mikä numero vastaa mitäkin palvelua. Tämä onnistuisi esim. näin (kopioitu AndroidStudion esimerkkitiedostoista)

`public class Palvelu {
    public interface Tyyppi {
        int ERROR = -1;
        int CONNECT_SUCCESS = 0;
        int GET_INPUT_STREAM_SUCCESS = 1;
        int PROCESS_INPUT_STREAM_IN_PROGRESS = 2;
        int PROCESS_INPUT_STREAM_SUCCESS = 3;
    }`

Eli siis käytettäisiin luokan sisäistä rajapintaa "Tyyppi". Palvelun tyypin voisi asettaa sitten esim näin. `Palvelu palvelu = new Palvelu();
palvelu.setTyyppi(Palvelu.Tyyppi.REKIAJELU);`

**Comment by tuomasme** [comment]
Yritin tehdä tuon rajapinnan. Toivottavasti tein mitä piti. Selostuksessa ei joka tapauksessa vikaa.

**Comment by bsuuv** [comment]
Erinomaista!
