### ISSUE TITLE
MokkiDAOn listaa funktio toimii vain kun toimintaAlueid on 3

### ISSUE THREAD

**Issue by Vilirazi** [bsuuv/Village-Newbies#46]
Mokkienhallinta-luokkan funktio listaaMokit toimii vain silloin, kun toimintaAlueId on 3, kaikilla muilla arvoilla heittää SQL exceptionin joka väittää ongelman olevan MokkiDAO:ssa executeQuery funktiossa

**Comment by bsuuv** [comment]
Mokkiluokat testattu ja samat bugit korjattu kuin aiemmissakin luokissa. Vieläkö tämä bugi on olemassa? Mm. tuo metodi meni kokonaan uusiksi.
